kind: pipeline
name: default
type: kubernetes

steps:
  - name: vendor
    image: golang
    commands:
      - go mod vendor

  - name: test
    image: golang
    commands:
      - make testnolint
  
  - name: prepare
    image: golang
    commands:
      - make grpc_health_probe indexer-countries

  - name: build
    image: docker
    settings:
      dockerfile: cmd/insided/Dockerfile
