kind: pipeline
name: default
type: kubernetes

steps:
  - name: test
    image: golang
    commands:
      - go test ./...
  
  - name: prepage
    image: golang
    commands:
      - make grpc_health_probe indexer-countries

  - name: build
    image: docker
    settings:
      dockerfile: cmd/insided/Dockerfile
