kind: pipeline
name: default
type: kubernetes

steps:
  - name: vendor
    image: golang
    commands:
      - go mod vendor

  - name: test
    image: golang
    commands:
      - make testnolint
  
  - name: build
    image: golang
    commands:
      - make grpc_health_probe insided indexer-countries

  - name: build-image
    image: plugins/docker
    settings:
      username: akhenakh
      password:
        from_secret: docker_password
      repo: akhenakh/insideout-demo
      context: cmd/insided
      dockerfile: cmd/insided/Dockerfile
