kind: pipeline
name: default
type: kubernetes

steps:
  - name: vendor
    image: golang:1.16-alpine
    commands:
      - go mod vendor

  - name: test
    image: golang:1.16-alpine
    commands:
      - make testnolint

  - name: proto-lint
    image: bufbuild/buf:0.41.0
    commands:
      - buf lint

  - name: build
    image: golang:1.16-alpine
    commands:
      - apk add musl-dev make
      - make grpc_health_probe insided indexer-countries

  - name: build-image
    image: plugins/docker
    settings:
      username: akhenakh
      password:
        from_secret: docker_password
      repo: akhenakh/insideout-demo
      context: cmd/insided
      dockerfile: cmd/insided/Dockerfile
