// Code generated by protoc-gen-go. DO NOT EDIT.
// source: insidesvc.proto

package insidesvc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _struct "github.com/golang/protobuf/ptypes/struct"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Geometry_Type int32

const (
	Geometry_POINT        Geometry_Type = 0
	Geometry_POLYGON      Geometry_Type = 1
	Geometry_MULTIPOLYGON Geometry_Type = 2
	Geometry_LINESTRING   Geometry_Type = 3
)

var Geometry_Type_name = map[int32]string{
	0: "POINT",
	1: "POLYGON",
	2: "MULTIPOLYGON",
	3: "LINESTRING",
}
var Geometry_Type_value = map[string]int32{
	"POINT":        0,
	"POLYGON":      1,
	"MULTIPOLYGON": 2,
	"LINESTRING":   3,
}

func (x Geometry_Type) String() string {
	return proto.EnumName(Geometry_Type_name, int32(x))
}
func (Geometry_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_insidesvc_75a12e6b037db9ab, []int{5, 0}
}

type WithinRequest struct {
	Lat float64 `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng float64 `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	// return features geometries or not
	// saving extra bytes
	RemoveGeometries bool `protobuf:"varint,3,opt,name=remove_geometries,json=removeGeometries,proto3" json:"remove_geometries,omitempty"`
	// comma separated list of property so returns to save extra bytes, leave empty for all
	SelectProperties     string   `protobuf:"bytes,4,opt,name=select_properties,json=selectProperties,proto3" json:"select_properties,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithinRequest) Reset()         { *m = WithinRequest{} }
func (m *WithinRequest) String() string { return proto.CompactTextString(m) }
func (*WithinRequest) ProtoMessage()    {}
func (*WithinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_insidesvc_75a12e6b037db9ab, []int{0}
}
func (m *WithinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithinRequest.Unmarshal(m, b)
}
func (m *WithinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithinRequest.Marshal(b, m, deterministic)
}
func (dst *WithinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithinRequest.Merge(dst, src)
}
func (m *WithinRequest) XXX_Size() int {
	return xxx_messageInfo_WithinRequest.Size(m)
}
func (m *WithinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WithinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WithinRequest proto.InternalMessageInfo

func (m *WithinRequest) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *WithinRequest) GetLng() float64 {
	if m != nil {
		return m.Lng
	}
	return 0
}

func (m *WithinRequest) GetRemoveGeometries() bool {
	if m != nil {
		return m.RemoveGeometries
	}
	return false
}

func (m *WithinRequest) GetSelectProperties() string {
	if m != nil {
		return m.SelectProperties
	}
	return ""
}

type WithinResponse struct {
	Point                *Point             `protobuf:"bytes,1,opt,name=point,proto3" json:"point,omitempty"`
	Responses            []*FeatureResponse `protobuf:"bytes,2,rep,name=responses,proto3" json:"responses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *WithinResponse) Reset()         { *m = WithinResponse{} }
func (m *WithinResponse) String() string { return proto.CompactTextString(m) }
func (*WithinResponse) ProtoMessage()    {}
func (*WithinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_insidesvc_75a12e6b037db9ab, []int{1}
}
func (m *WithinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithinResponse.Unmarshal(m, b)
}
func (m *WithinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithinResponse.Marshal(b, m, deterministic)
}
func (dst *WithinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithinResponse.Merge(dst, src)
}
func (m *WithinResponse) XXX_Size() int {
	return xxx_messageInfo_WithinResponse.Size(m)
}
func (m *WithinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WithinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WithinResponse proto.InternalMessageInfo

func (m *WithinResponse) GetPoint() *Point {
	if m != nil {
		return m.Point
	}
	return nil
}

func (m *WithinResponse) GetResponses() []*FeatureResponse {
	if m != nil {
		return m.Responses
	}
	return nil
}

type GetRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_insidesvc_75a12e6b037db9ab, []int{2}
}
func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (dst *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(dst, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type FeatureResponse struct {
	// id in the index
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Feature              *Feature `protobuf:"bytes,3,opt,name=feature,proto3" json:"feature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeatureResponse) Reset()         { *m = FeatureResponse{} }
func (m *FeatureResponse) String() string { return proto.CompactTextString(m) }
func (*FeatureResponse) ProtoMessage()    {}
func (*FeatureResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_insidesvc_75a12e6b037db9ab, []int{3}
}
func (m *FeatureResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeatureResponse.Unmarshal(m, b)
}
func (m *FeatureResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeatureResponse.Marshal(b, m, deterministic)
}
func (dst *FeatureResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeatureResponse.Merge(dst, src)
}
func (m *FeatureResponse) XXX_Size() int {
	return xxx_messageInfo_FeatureResponse.Size(m)
}
func (m *FeatureResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FeatureResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FeatureResponse proto.InternalMessageInfo

func (m *FeatureResponse) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FeatureResponse) GetFeature() *Feature {
	if m != nil {
		return m.Feature
	}
	return nil
}

type Feature struct {
	Geometry             *Geometry                 `protobuf:"bytes,1,opt,name=geometry,proto3" json:"geometry,omitempty"`
	Properties           map[string]*_struct.Value `protobuf:"bytes,2,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *Feature) Reset()         { *m = Feature{} }
func (m *Feature) String() string { return proto.CompactTextString(m) }
func (*Feature) ProtoMessage()    {}
func (*Feature) Descriptor() ([]byte, []int) {
	return fileDescriptor_insidesvc_75a12e6b037db9ab, []int{4}
}
func (m *Feature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Feature.Unmarshal(m, b)
}
func (m *Feature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Feature.Marshal(b, m, deterministic)
}
func (dst *Feature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Feature.Merge(dst, src)
}
func (m *Feature) XXX_Size() int {
	return xxx_messageInfo_Feature.Size(m)
}
func (m *Feature) XXX_DiscardUnknown() {
	xxx_messageInfo_Feature.DiscardUnknown(m)
}

var xxx_messageInfo_Feature proto.InternalMessageInfo

func (m *Feature) GetGeometry() *Geometry {
	if m != nil {
		return m.Geometry
	}
	return nil
}

func (m *Feature) GetProperties() map[string]*_struct.Value {
	if m != nil {
		return m.Properties
	}
	return nil
}

type Geometry struct {
	Type                 Geometry_Type `protobuf:"varint,1,opt,name=type,proto3,enum=Geometry_Type" json:"type,omitempty"`
	Geometries           []*Geometry   `protobuf:"bytes,2,rep,name=geometries,proto3" json:"geometries,omitempty"`
	Coordinates          []float64     `protobuf:"fixed64,3,rep,packed,name=coordinates,proto3" json:"coordinates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Geometry) Reset()         { *m = Geometry{} }
func (m *Geometry) String() string { return proto.CompactTextString(m) }
func (*Geometry) ProtoMessage()    {}
func (*Geometry) Descriptor() ([]byte, []int) {
	return fileDescriptor_insidesvc_75a12e6b037db9ab, []int{5}
}
func (m *Geometry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Geometry.Unmarshal(m, b)
}
func (m *Geometry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Geometry.Marshal(b, m, deterministic)
}
func (dst *Geometry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Geometry.Merge(dst, src)
}
func (m *Geometry) XXX_Size() int {
	return xxx_messageInfo_Geometry.Size(m)
}
func (m *Geometry) XXX_DiscardUnknown() {
	xxx_messageInfo_Geometry.DiscardUnknown(m)
}

var xxx_messageInfo_Geometry proto.InternalMessageInfo

func (m *Geometry) GetType() Geometry_Type {
	if m != nil {
		return m.Type
	}
	return Geometry_POINT
}

func (m *Geometry) GetGeometries() []*Geometry {
	if m != nil {
		return m.Geometries
	}
	return nil
}

func (m *Geometry) GetCoordinates() []float64 {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

type Point struct {
	Lat                  float64  `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng                  float64  `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Point) Reset()         { *m = Point{} }
func (m *Point) String() string { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()    {}
func (*Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_insidesvc_75a12e6b037db9ab, []int{6}
}
func (m *Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Point.Unmarshal(m, b)
}
func (m *Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Point.Marshal(b, m, deterministic)
}
func (dst *Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Point.Merge(dst, src)
}
func (m *Point) XXX_Size() int {
	return xxx_messageInfo_Point.Size(m)
}
func (m *Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Point proto.InternalMessageInfo

func (m *Point) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Point) GetLng() float64 {
	if m != nil {
		return m.Lng
	}
	return 0
}

func init() {
	proto.RegisterType((*WithinRequest)(nil), "WithinRequest")
	proto.RegisterType((*WithinResponse)(nil), "WithinResponse")
	proto.RegisterType((*GetRequest)(nil), "GetRequest")
	proto.RegisterType((*FeatureResponse)(nil), "FeatureResponse")
	proto.RegisterType((*Feature)(nil), "Feature")
	proto.RegisterMapType((map[string]*_struct.Value)(nil), "Feature.PropertiesEntry")
	proto.RegisterType((*Geometry)(nil), "Geometry")
	proto.RegisterType((*Point)(nil), "Point")
	proto.RegisterEnum("Geometry_Type", Geometry_Type_name, Geometry_Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// InsideClient is the client API for Inside service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InsideClient interface {
	//  Stab returns features containing lat lng
	Within(ctx context.Context, in *WithinRequest, opts ...grpc.CallOption) (*WithinResponse, error)
	// Get returns a feature by its ID
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Feature, error)
}

type insideClient struct {
	cc *grpc.ClientConn
}

func NewInsideClient(cc *grpc.ClientConn) InsideClient {
	return &insideClient{cc}
}

func (c *insideClient) Within(ctx context.Context, in *WithinRequest, opts ...grpc.CallOption) (*WithinResponse, error) {
	out := new(WithinResponse)
	err := c.cc.Invoke(ctx, "/Inside/Within", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *insideClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Feature, error) {
	out := new(Feature)
	err := c.cc.Invoke(ctx, "/Inside/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InsideServer is the server API for Inside service.
type InsideServer interface {
	//  Stab returns features containing lat lng
	Within(context.Context, *WithinRequest) (*WithinResponse, error)
	// Get returns a feature by its ID
	Get(context.Context, *GetRequest) (*Feature, error)
}

func RegisterInsideServer(s *grpc.Server, srv InsideServer) {
	s.RegisterService(&_Inside_serviceDesc, srv)
}

func _Inside_Within_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InsideServer).Within(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Inside/Within",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InsideServer).Within(ctx, req.(*WithinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inside_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InsideServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Inside/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InsideServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Inside_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Inside",
	HandlerType: (*InsideServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Within",
			Handler:    _Inside_Within_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Inside_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "insidesvc.proto",
}

func init() { proto.RegisterFile("insidesvc.proto", fileDescriptor_insidesvc_75a12e6b037db9ab) }

var fileDescriptor_insidesvc_75a12e6b037db9ab = []byte{
	// 507 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xcd, 0x8e, 0xda, 0x3c,
	0x14, 0xc5, 0x09, 0xbf, 0x37, 0xdf, 0x84, 0x7c, 0x5e, 0x54, 0x08, 0xa1, 0x0a, 0x59, 0xaa, 0x44,
	0x45, 0xe5, 0x91, 0xd2, 0xcd, 0xa8, 0xab, 0x6e, 0x28, 0x42, 0xa2, 0x80, 0x5c, 0x68, 0xd5, 0x4d,
	0x47, 0x0c, 0xdc, 0xa1, 0x51, 0x99, 0x38, 0x4d, 0x1c, 0x24, 0x1e, 0xa2, 0x8f, 0xd4, 0x45, 0xdf,
	0xac, 0x8a, 0x9d, 0x84, 0x0c, 0xab, 0xee, 0xec, 0x73, 0x8e, 0xaf, 0xef, 0xb9, 0x3e, 0x86, 0x6e,
	0x10, 0x26, 0xc1, 0x1e, 0x93, 0xd3, 0x8e, 0x47, 0xb1, 0x54, 0xb2, 0x3f, 0x38, 0x48, 0x79, 0x38,
	0xe2, 0xad, 0xde, 0x3d, 0xa4, 0x8f, 0xb7, 0x89, 0x8a, 0xd3, 0x9d, 0x32, 0x2c, 0xfb, 0x45, 0xe0,
	0xe6, 0x4b, 0xa0, 0xbe, 0x07, 0xa1, 0xc0, 0x9f, 0x29, 0x26, 0x8a, 0x7a, 0x60, 0x1f, 0xb7, 0xaa,
	0x47, 0x86, 0x64, 0x44, 0x44, 0xb6, 0xd4, 0x48, 0x78, 0xe8, 0x59, 0x39, 0x12, 0x1e, 0xe8, 0x18,
	0xfe, 0x8f, 0xf1, 0x49, 0x9e, 0xf0, 0xfe, 0x80, 0xf2, 0x09, 0x55, 0x1c, 0x60, 0xd2, 0xb3, 0x87,
	0x64, 0xd4, 0x16, 0x9e, 0x21, 0xa6, 0x25, 0x9e, 0x89, 0x13, 0x3c, 0xe2, 0x4e, 0xdd, 0x47, 0xb1,
	0x8c, 0x30, 0x56, 0x99, 0xb8, 0x3e, 0x24, 0xa3, 0x8e, 0xf0, 0x0c, 0xb1, 0x2a, 0x71, 0xf6, 0x0d,
	0xdc, 0xa2, 0x9d, 0x24, 0x92, 0x61, 0x82, 0x74, 0x00, 0x8d, 0x48, 0x06, 0xa1, 0xe9, 0xc8, 0xf1,
	0x9b, 0x7c, 0x95, 0xed, 0x84, 0x01, 0x29, 0x87, 0x4e, 0x9c, 0x2b, 0x93, 0x9e, 0x35, 0xb4, 0x47,
	0x8e, 0xef, 0xf1, 0x0f, 0xb8, 0x55, 0x69, 0x8c, 0x45, 0x09, 0x71, 0x91, 0xb0, 0x01, 0xc0, 0x14,
	0x55, 0xe1, 0xd5, 0x05, 0x2b, 0xd8, 0xeb, 0xc2, 0x37, 0xc2, 0x0a, 0xf6, 0x6c, 0x02, 0xdd, 0xab,
	0xb3, 0xd7, 0x12, 0xca, 0xa0, 0xf5, 0x68, 0x24, 0xda, 0xb0, 0xe3, 0xb7, 0xcb, 0xeb, 0x0a, 0x82,
	0xfd, 0x21, 0xd0, 0xca, 0x41, 0xfa, 0x0a, 0xda, 0xf9, 0x8c, 0xce, 0xb9, 0x83, 0x0e, 0xcf, 0x87,
	0x73, 0x16, 0x25, 0x45, 0xef, 0x00, 0x2a, 0xd3, 0x31, 0x46, 0x7a, 0x45, 0x65, 0x7e, 0x19, 0xd0,
	0x24, 0xcc, 0xce, 0x55, 0xb4, 0xfd, 0x0d, 0x74, 0xaf, 0xe8, 0xec, 0xc1, 0x7e, 0xa0, 0xb9, 0xae,
	0x23, 0xb2, 0x25, 0x7d, 0x03, 0x8d, 0xd3, 0xf6, 0x98, 0xa2, 0x7e, 0x44, 0xc7, 0x7f, 0xc1, 0x4d,
	0x28, 0x78, 0x11, 0x0a, 0xfe, 0x39, 0x63, 0x85, 0x11, 0xbd, 0xb3, 0xee, 0x08, 0xfb, 0x4d, 0xa0,
	0x5d, 0xf4, 0x49, 0x19, 0xd4, 0xd5, 0x39, 0x42, 0x5d, 0xd1, 0xf5, 0xdd, 0xd2, 0x00, 0x5f, 0x9f,
	0x23, 0x14, 0x9a, 0xa3, 0xaf, 0x01, 0x2a, 0x61, 0x30, 0x0e, 0x2a, 0x56, 0x2b, 0x24, 0x1d, 0x82,
	0xb3, 0x93, 0x32, 0xde, 0x07, 0xe1, 0x56, 0xe9, 0xe0, 0xd8, 0x23, 0x22, 0xaa, 0x10, 0x7b, 0x0f,
	0xf5, 0xac, 0x34, 0xed, 0x40, 0x63, 0xb5, 0x9c, 0x2d, 0xd6, 0x5e, 0x8d, 0x3a, 0xd0, 0x5a, 0x2d,
	0xe7, 0x5f, 0xa7, 0xcb, 0x85, 0x47, 0xa8, 0x07, 0xff, 0x7d, 0xdc, 0xcc, 0xd7, 0xb3, 0x02, 0xb1,
	0xa8, 0x0b, 0x30, 0x9f, 0x2d, 0x26, 0x9f, 0xd6, 0x62, 0xb6, 0x98, 0x7a, 0x36, 0x1b, 0x43, 0x43,
	0x07, 0xe5, 0x5f, 0xf2, 0xec, 0x6f, 0xa0, 0x39, 0xd3, 0xdf, 0x86, 0x8e, 0xa1, 0x69, 0xf2, 0x47,
	0x5d, 0xfe, 0xec, 0x5f, 0xf4, 0xbb, 0xfc, 0x79, 0x30, 0x59, 0x8d, 0xbe, 0x04, 0x7b, 0x8a, 0x8a,
	0x3a, 0xfc, 0x12, 0xa9, 0x7e, 0x19, 0x07, 0x56, 0x7b, 0x68, 0xea, 0xf1, 0xbe, 0xfd, 0x1b, 0x00,
	0x00, 0xff, 0xff, 0x9b, 0xca, 0x7a, 0xcc, 0x94, 0x03, 0x00, 0x00,
}
