// Code generated by protoc-gen-go. DO NOT EDIT.
// source: insidesvc.proto

package insidesvc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _struct "github.com/golang/protobuf/ptypes/struct"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Geometry_Type int32

const (
	Geometry_POINT        Geometry_Type = 0
	Geometry_POLYGON      Geometry_Type = 1
	Geometry_MULTIPOLYGON Geometry_Type = 2
	Geometry_LINESTRING   Geometry_Type = 3
)

var Geometry_Type_name = map[int32]string{
	0: "POINT",
	1: "POLYGON",
	2: "MULTIPOLYGON",
	3: "LINESTRING",
}
var Geometry_Type_value = map[string]int32{
	"POINT":        0,
	"POLYGON":      1,
	"MULTIPOLYGON": 2,
	"LINESTRING":   3,
}

func (x Geometry_Type) String() string {
	return proto.EnumName(Geometry_Type_name, int32(x))
}
func (Geometry_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_insidesvc_4b1db79cd52e05d8, []int{6, 0}
}

type WithinRequest struct {
	Lat float64 `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng float64 `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	// return features geometries or not
	// saving extra bytes
	RemoveGeometries bool `protobuf:"varint,3,opt,name=remove_geometries,json=removeGeometries,proto3" json:"remove_geometries,omitempty"`
	// comma separated list of property to returns to save extra bytes, leave empty for all
	SelectProperties     string   `protobuf:"bytes,4,opt,name=select_properties,json=selectProperties,proto3" json:"select_properties,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WithinRequest) Reset()         { *m = WithinRequest{} }
func (m *WithinRequest) String() string { return proto.CompactTextString(m) }
func (*WithinRequest) ProtoMessage()    {}
func (*WithinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_insidesvc_4b1db79cd52e05d8, []int{0}
}
func (m *WithinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithinRequest.Unmarshal(m, b)
}
func (m *WithinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithinRequest.Marshal(b, m, deterministic)
}
func (dst *WithinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithinRequest.Merge(dst, src)
}
func (m *WithinRequest) XXX_Size() int {
	return xxx_messageInfo_WithinRequest.Size(m)
}
func (m *WithinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WithinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WithinRequest proto.InternalMessageInfo

func (m *WithinRequest) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *WithinRequest) GetLng() float64 {
	if m != nil {
		return m.Lng
	}
	return 0
}

func (m *WithinRequest) GetRemoveGeometries() bool {
	if m != nil {
		return m.RemoveGeometries
	}
	return false
}

func (m *WithinRequest) GetSelectProperties() string {
	if m != nil {
		return m.SelectProperties
	}
	return ""
}

type RectSearchRequest struct {
	Urlat float64 `protobuf:"fixed64,1,opt,name=urlat,proto3" json:"urlat,omitempty"`
	Urlng float64 `protobuf:"fixed64,2,opt,name=urlng,proto3" json:"urlng,omitempty"`
	Bllat float64 `protobuf:"fixed64,3,opt,name=bllat,proto3" json:"bllat,omitempty"`
	Bllng float64 `protobuf:"fixed64,4,opt,name=bllng,proto3" json:"bllng,omitempty"`
	// return features geometries or not
	// saving extra bytes
	RemoveGeometries bool `protobuf:"varint,5,opt,name=remove_geometries,json=removeGeometries,proto3" json:"remove_geometries,omitempty"`
	// comma separated list of property to returns to save extra bytes, leave empty for all
	SelectProperties     string   `protobuf:"bytes,6,opt,name=select_properties,json=selectProperties,proto3" json:"select_properties,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RectSearchRequest) Reset()         { *m = RectSearchRequest{} }
func (m *RectSearchRequest) String() string { return proto.CompactTextString(m) }
func (*RectSearchRequest) ProtoMessage()    {}
func (*RectSearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_insidesvc_4b1db79cd52e05d8, []int{1}
}
func (m *RectSearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RectSearchRequest.Unmarshal(m, b)
}
func (m *RectSearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RectSearchRequest.Marshal(b, m, deterministic)
}
func (dst *RectSearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RectSearchRequest.Merge(dst, src)
}
func (m *RectSearchRequest) XXX_Size() int {
	return xxx_messageInfo_RectSearchRequest.Size(m)
}
func (m *RectSearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RectSearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RectSearchRequest proto.InternalMessageInfo

func (m *RectSearchRequest) GetUrlat() float64 {
	if m != nil {
		return m.Urlat
	}
	return 0
}

func (m *RectSearchRequest) GetUrlng() float64 {
	if m != nil {
		return m.Urlng
	}
	return 0
}

func (m *RectSearchRequest) GetBllat() float64 {
	if m != nil {
		return m.Bllat
	}
	return 0
}

func (m *RectSearchRequest) GetBllng() float64 {
	if m != nil {
		return m.Bllng
	}
	return 0
}

func (m *RectSearchRequest) GetRemoveGeometries() bool {
	if m != nil {
		return m.RemoveGeometries
	}
	return false
}

func (m *RectSearchRequest) GetSelectProperties() string {
	if m != nil {
		return m.SelectProperties
	}
	return ""
}

type FeaturesResponse struct {
	Responses            []*FeatureResponse `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *FeaturesResponse) Reset()         { *m = FeaturesResponse{} }
func (m *FeaturesResponse) String() string { return proto.CompactTextString(m) }
func (*FeaturesResponse) ProtoMessage()    {}
func (*FeaturesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_insidesvc_4b1db79cd52e05d8, []int{2}
}
func (m *FeaturesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeaturesResponse.Unmarshal(m, b)
}
func (m *FeaturesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeaturesResponse.Marshal(b, m, deterministic)
}
func (dst *FeaturesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeaturesResponse.Merge(dst, src)
}
func (m *FeaturesResponse) XXX_Size() int {
	return xxx_messageInfo_FeaturesResponse.Size(m)
}
func (m *FeaturesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FeaturesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FeaturesResponse proto.InternalMessageInfo

func (m *FeaturesResponse) GetResponses() []*FeatureResponse {
	if m != nil {
		return m.Responses
	}
	return nil
}

type FeatureResponse struct {
	// id in the index
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Feature              *Feature `protobuf:"bytes,3,opt,name=feature,proto3" json:"feature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeatureResponse) Reset()         { *m = FeatureResponse{} }
func (m *FeatureResponse) String() string { return proto.CompactTextString(m) }
func (*FeatureResponse) ProtoMessage()    {}
func (*FeatureResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_insidesvc_4b1db79cd52e05d8, []int{3}
}
func (m *FeatureResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeatureResponse.Unmarshal(m, b)
}
func (m *FeatureResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeatureResponse.Marshal(b, m, deterministic)
}
func (dst *FeatureResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeatureResponse.Merge(dst, src)
}
func (m *FeatureResponse) XXX_Size() int {
	return xxx_messageInfo_FeatureResponse.Size(m)
}
func (m *FeatureResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FeatureResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FeatureResponse proto.InternalMessageInfo

func (m *FeatureResponse) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FeatureResponse) GetFeature() *Feature {
	if m != nil {
		return m.Feature
	}
	return nil
}

type GetRequest struct {
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// internally stored as uint16
	LoopIndex            uint32   `protobuf:"varint,2,opt,name=loop_index,json=loopIndex,proto3" json:"loop_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_insidesvc_4b1db79cd52e05d8, []int{4}
}
func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (dst *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(dst, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetRequest) GetLoopIndex() uint32 {
	if m != nil {
		return m.LoopIndex
	}
	return 0
}

type Feature struct {
	Geometry             *Geometry                 `protobuf:"bytes,1,opt,name=geometry,proto3" json:"geometry,omitempty"`
	Properties           map[string]*_struct.Value `protobuf:"bytes,2,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *Feature) Reset()         { *m = Feature{} }
func (m *Feature) String() string { return proto.CompactTextString(m) }
func (*Feature) ProtoMessage()    {}
func (*Feature) Descriptor() ([]byte, []int) {
	return fileDescriptor_insidesvc_4b1db79cd52e05d8, []int{5}
}
func (m *Feature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Feature.Unmarshal(m, b)
}
func (m *Feature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Feature.Marshal(b, m, deterministic)
}
func (dst *Feature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Feature.Merge(dst, src)
}
func (m *Feature) XXX_Size() int {
	return xxx_messageInfo_Feature.Size(m)
}
func (m *Feature) XXX_DiscardUnknown() {
	xxx_messageInfo_Feature.DiscardUnknown(m)
}

var xxx_messageInfo_Feature proto.InternalMessageInfo

func (m *Feature) GetGeometry() *Geometry {
	if m != nil {
		return m.Geometry
	}
	return nil
}

func (m *Feature) GetProperties() map[string]*_struct.Value {
	if m != nil {
		return m.Properties
	}
	return nil
}

type Geometry struct {
	Type                 Geometry_Type `protobuf:"varint,1,opt,name=type,proto3,enum=Geometry_Type" json:"type,omitempty"`
	Geometries           []*Geometry   `protobuf:"bytes,2,rep,name=geometries,proto3" json:"geometries,omitempty"`
	Coordinates          []float64     `protobuf:"fixed64,3,rep,packed,name=coordinates,proto3" json:"coordinates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Geometry) Reset()         { *m = Geometry{} }
func (m *Geometry) String() string { return proto.CompactTextString(m) }
func (*Geometry) ProtoMessage()    {}
func (*Geometry) Descriptor() ([]byte, []int) {
	return fileDescriptor_insidesvc_4b1db79cd52e05d8, []int{6}
}
func (m *Geometry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Geometry.Unmarshal(m, b)
}
func (m *Geometry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Geometry.Marshal(b, m, deterministic)
}
func (dst *Geometry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Geometry.Merge(dst, src)
}
func (m *Geometry) XXX_Size() int {
	return xxx_messageInfo_Geometry.Size(m)
}
func (m *Geometry) XXX_DiscardUnknown() {
	xxx_messageInfo_Geometry.DiscardUnknown(m)
}

var xxx_messageInfo_Geometry proto.InternalMessageInfo

func (m *Geometry) GetType() Geometry_Type {
	if m != nil {
		return m.Type
	}
	return Geometry_POINT
}

func (m *Geometry) GetGeometries() []*Geometry {
	if m != nil {
		return m.Geometries
	}
	return nil
}

func (m *Geometry) GetCoordinates() []float64 {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

type Point struct {
	Lat                  float64  `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng                  float64  `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Point) Reset()         { *m = Point{} }
func (m *Point) String() string { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()    {}
func (*Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_insidesvc_4b1db79cd52e05d8, []int{7}
}
func (m *Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Point.Unmarshal(m, b)
}
func (m *Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Point.Marshal(b, m, deterministic)
}
func (dst *Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Point.Merge(dst, src)
}
func (m *Point) XXX_Size() int {
	return xxx_messageInfo_Point.Size(m)
}
func (m *Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Point proto.InternalMessageInfo

func (m *Point) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Point) GetLng() float64 {
	if m != nil {
		return m.Lng
	}
	return 0
}

func init() {
	proto.RegisterType((*WithinRequest)(nil), "WithinRequest")
	proto.RegisterType((*RectSearchRequest)(nil), "RectSearchRequest")
	proto.RegisterType((*FeaturesResponse)(nil), "FeaturesResponse")
	proto.RegisterType((*FeatureResponse)(nil), "FeatureResponse")
	proto.RegisterType((*GetRequest)(nil), "GetRequest")
	proto.RegisterType((*Feature)(nil), "Feature")
	proto.RegisterMapType((map[string]*_struct.Value)(nil), "Feature.PropertiesEntry")
	proto.RegisterType((*Geometry)(nil), "Geometry")
	proto.RegisterType((*Point)(nil), "Point")
	proto.RegisterEnum("Geometry_Type", Geometry_Type_name, Geometry_Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// InsideClient is the client API for Inside service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InsideClient interface {
	//  Stab returns features containing lat lng
	Within(ctx context.Context, in *WithinRequest, opts ...grpc.CallOption) (*FeaturesResponse, error)
	// returns features intersecting rect
	RectSearch(ctx context.Context, in *RectSearchRequest, opts ...grpc.CallOption) (*FeaturesResponse, error)
	// Get returns a feature by its internal ID and polygon index
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Feature, error)
}

type insideClient struct {
	cc *grpc.ClientConn
}

func NewInsideClient(cc *grpc.ClientConn) InsideClient {
	return &insideClient{cc}
}

func (c *insideClient) Within(ctx context.Context, in *WithinRequest, opts ...grpc.CallOption) (*FeaturesResponse, error) {
	out := new(FeaturesResponse)
	err := c.cc.Invoke(ctx, "/Inside/Within", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *insideClient) RectSearch(ctx context.Context, in *RectSearchRequest, opts ...grpc.CallOption) (*FeaturesResponse, error) {
	out := new(FeaturesResponse)
	err := c.cc.Invoke(ctx, "/Inside/RectSearch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *insideClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Feature, error) {
	out := new(Feature)
	err := c.cc.Invoke(ctx, "/Inside/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InsideServer is the server API for Inside service.
type InsideServer interface {
	//  Stab returns features containing lat lng
	Within(context.Context, *WithinRequest) (*FeaturesResponse, error)
	// returns features intersecting rect
	RectSearch(context.Context, *RectSearchRequest) (*FeaturesResponse, error)
	// Get returns a feature by its internal ID and polygon index
	Get(context.Context, *GetRequest) (*Feature, error)
}

func RegisterInsideServer(s *grpc.Server, srv InsideServer) {
	s.RegisterService(&_Inside_serviceDesc, srv)
}

func _Inside_Within_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InsideServer).Within(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Inside/Within",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InsideServer).Within(ctx, req.(*WithinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inside_RectSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RectSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InsideServer).RectSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Inside/RectSearch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InsideServer).RectSearch(ctx, req.(*RectSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inside_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InsideServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Inside/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InsideServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Inside_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Inside",
	HandlerType: (*InsideServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Within",
			Handler:    _Inside_Within_Handler,
		},
		{
			MethodName: "RectSearch",
			Handler:    _Inside_RectSearch_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Inside_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "insidesvc.proto",
}

func init() { proto.RegisterFile("insidesvc.proto", fileDescriptor_insidesvc_4b1db79cd52e05d8) }

var fileDescriptor_insidesvc_4b1db79cd52e05d8 = []byte{
	// 587 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x51, 0x6b, 0x13, 0x4d,
	0x14, 0xed, 0x64, 0x9b, 0x34, 0xb9, 0xfb, 0x35, 0xdd, 0x0e, 0x1f, 0x12, 0x82, 0x4a, 0x18, 0x10,
	0x22, 0xd5, 0x29, 0x44, 0x84, 0xa2, 0x2f, 0x22, 0xd4, 0x10, 0xa8, 0x69, 0x98, 0xa6, 0x8a, 0x4f,
	0x25, 0xdd, 0xdc, 0x6e, 0x17, 0xb7, 0x3b, 0xeb, 0xee, 0x6c, 0x31, 0x3f, 0x42, 0xff, 0x91, 0x0f,
	0x3e, 0xf8, 0xbf, 0x64, 0x66, 0x76, 0x37, 0x6b, 0xb4, 0xa0, 0x6f, 0x73, 0xcf, 0x39, 0x73, 0xe7,
	0x9e, 0xbb, 0xf7, 0x2e, 0xec, 0x85, 0x71, 0x16, 0x2e, 0x31, 0xbb, 0xf5, 0x79, 0x92, 0x4a, 0x25,
	0xfb, 0xf7, 0x03, 0x29, 0x83, 0x08, 0x0f, 0x4d, 0x74, 0x99, 0x5f, 0x1d, 0x66, 0x2a, 0xcd, 0x7d,
	0x65, 0x59, 0xf6, 0x85, 0xc0, 0xee, 0xfb, 0x50, 0x5d, 0x87, 0xb1, 0xc0, 0x4f, 0x39, 0x66, 0x8a,
	0x7a, 0xe0, 0x44, 0x0b, 0xd5, 0x23, 0x03, 0x32, 0x24, 0x42, 0x1f, 0x0d, 0x12, 0x07, 0xbd, 0x46,
	0x81, 0xc4, 0x01, 0x3d, 0x80, 0xfd, 0x14, 0x6f, 0xe4, 0x2d, 0x5e, 0x04, 0x28, 0x6f, 0x50, 0xa5,
	0x21, 0x66, 0x3d, 0x67, 0x40, 0x86, 0x6d, 0xe1, 0x59, 0x62, 0x5c, 0xe1, 0x5a, 0x9c, 0x61, 0x84,
	0xbe, 0xba, 0x48, 0x52, 0x99, 0x60, 0xaa, 0xb4, 0x78, 0x7b, 0x40, 0x86, 0x1d, 0xe1, 0x59, 0x62,
	0x56, 0xe1, 0xec, 0x07, 0x81, 0x7d, 0x81, 0xbe, 0x3a, 0xc3, 0x45, 0xea, 0x5f, 0x97, 0x35, 0xfd,
	0x0f, 0xcd, 0x3c, 0x5d, 0x57, 0x65, 0x83, 0x02, 0xad, 0x2a, 0xb3, 0x81, 0x46, 0x2f, 0x23, 0xad,
	0x75, 0x2c, 0x6a, 0x82, 0x02, 0x8d, 0x03, 0xf3, 0xb0, 0x45, 0xef, 0xf2, 0xd1, 0xfc, 0x17, 0x1f,
	0xad, 0x3b, 0x7c, 0xbc, 0x06, 0xef, 0x0d, 0x2e, 0x54, 0x9e, 0x62, 0x26, 0x30, 0x4b, 0x64, 0x9c,
	0x21, 0xe5, 0xd0, 0x49, 0x8b, 0x73, 0xd6, 0x23, 0x03, 0x67, 0xe8, 0x8e, 0x3c, 0x5e, 0xa8, 0x4a,
	0x91, 0x58, 0x4b, 0xd8, 0x31, 0xec, 0x6d, 0xb0, 0xb4, 0x0b, 0x8d, 0x70, 0x69, 0xba, 0xb0, 0x2b,
	0x1a, 0xe1, 0x92, 0x32, 0xd8, 0xb9, 0xb2, 0x12, 0x63, 0xd7, 0x1d, 0xb5, 0xab, 0x84, 0x25, 0xc1,
	0x5e, 0x02, 0x8c, 0x51, 0x95, 0xad, 0xdc, 0xcc, 0xf0, 0x00, 0x20, 0x92, 0x32, 0xb9, 0x08, 0xe3,
	0x25, 0x7e, 0x36, 0x9d, 0xdc, 0x15, 0x1d, 0x8d, 0x4c, 0x34, 0xc0, 0xbe, 0x13, 0xd8, 0x29, 0x32,
	0xd2, 0x47, 0xd0, 0x2e, 0xda, 0xb4, 0x32, 0x09, 0xdc, 0x51, 0x87, 0x17, 0xfd, 0x59, 0x89, 0x8a,
	0xa2, 0x47, 0x00, 0xb5, 0x06, 0x35, 0x8c, 0xcf, 0x5e, 0x59, 0x16, 0x5f, 0xf7, 0xe8, 0x38, 0xd6,
	0xf7, 0x6a, 0xda, 0xfe, 0x39, 0xec, 0x6d, 0xd0, 0x7a, 0xf6, 0x3e, 0xa2, 0x7d, 0xae, 0x23, 0xf4,
	0x91, 0x3e, 0x81, 0xe6, 0xed, 0x22, 0xca, 0xd1, 0xd4, 0xea, 0x8e, 0xee, 0x71, 0x3b, 0xdf, 0xbc,
	0x9c, 0x6f, 0xfe, 0x4e, 0xb3, 0xc2, 0x8a, 0x5e, 0x34, 0x8e, 0x08, 0xfb, 0x46, 0xa0, 0x5d, 0xd6,
	0x49, 0x19, 0x6c, 0xab, 0x55, 0x82, 0x26, 0x63, 0x77, 0xd4, 0xad, 0x0c, 0xf0, 0xf9, 0x2a, 0x41,
	0x61, 0x38, 0xfa, 0x18, 0xa0, 0x36, 0x0f, 0xd6, 0x41, 0xcd, 0x6a, 0x8d, 0xa4, 0x03, 0x70, 0x7d,
	0x29, 0xd3, 0x65, 0x18, 0x2f, 0x94, 0xd9, 0x01, 0x67, 0x48, 0x44, 0x1d, 0x62, 0xaf, 0x60, 0x5b,
	0xa7, 0xa6, 0x1d, 0x68, 0xce, 0x4e, 0x27, 0xd3, 0xb9, 0xb7, 0x45, 0x5d, 0xd8, 0x99, 0x9d, 0x9e,
	0x7c, 0x18, 0x9f, 0x4e, 0x3d, 0x42, 0x3d, 0xf8, 0xef, 0xed, 0xf9, 0xc9, 0x7c, 0x52, 0x22, 0x0d,
	0xda, 0x05, 0x38, 0x99, 0x4c, 0x8f, 0xcf, 0xe6, 0x62, 0x32, 0x1d, 0x7b, 0x0e, 0x3b, 0x80, 0xe6,
	0x4c, 0x86, 0xf1, 0x5f, 0xad, 0xe6, 0xe8, 0x2b, 0x81, 0xd6, 0xc4, 0xfc, 0x02, 0xe8, 0x53, 0x68,
	0xd9, 0xd5, 0xa6, 0x5d, 0xfe, 0xcb, 0x8e, 0xf7, 0xf7, 0xf9, 0xe6, 0x70, 0xb2, 0x2d, 0xfa, 0x1c,
	0x60, 0xbd, 0x79, 0x94, 0xf2, 0xdf, 0xd6, 0xf0, 0xcf, 0xd7, 0x1e, 0x82, 0x33, 0x46, 0x45, 0x5d,
	0xbe, 0x1e, 0xb2, 0x7e, 0x35, 0x85, 0x6c, 0xeb, 0xb2, 0x65, 0x3e, 0xcc, 0xb3, 0x9f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xed, 0xb9, 0xc9, 0xc1, 0x99, 0x04, 0x00, 0x00,
}
