---

apiVersion: v1
kind: Service
metadata:
  name: insided-http
  labels:
    name: insided-http
    type: "http"
spec:
  ports:
    - port: 8080
      name: "http"
      targetPort: http
      protocol: TCP
  selector:
    app: insided
  clusterIP: None
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: frcommunes-ingress
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`frcommunes.dev.inair.space`)
      middlewares:
        - name: compress
        - name: ratelimit4s
      kind: Rule
      services:
        - name: insided-http
          port: 8080
  tls:
    certResolver: default
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: frcommunes-80-ingress
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`frcommunes.dev.inair.space`)
      middlewares:
        - name: https-only
      kind: Rule
      services:
        - name: insided-http
          port: 8080